// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvn6YhEBLfK85BBbrch4wzagTAnN3r_1w',
    appId: '1:879205408677:web:352bb73e4c22cb9dee924c',
    messagingSenderId: '879205408677',
    projectId: 'schaty-7b3c3',
    authDomain: 'schaty-7b3c3.firebaseapp.com',
    databaseURL: 'https://schaty-7b3c3.firebaseio.com',
    storageBucket: 'schaty-7b3c3.appspot.com',
    measurementId: 'G-RD152X8639',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnt0n3mSl8gEwp1omTtKjIMjhWOnmRTmc',
    appId: '1:879205408677:android:701649773e45c911ee924c',
    messagingSenderId: '879205408677',
    projectId: 'schaty-7b3c3',
    databaseURL: 'https://schaty-7b3c3.firebaseio.com',
    storageBucket: 'schaty-7b3c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgid1GAhGFUvRz7OdR7oOUIoN5FnCv0cI',
    appId: '1:879205408677:ios:5d5eb1ef3d4743cbee924c',
    messagingSenderId: '879205408677',
    projectId: 'schaty-7b3c3',
    databaseURL: 'https://schaty-7b3c3.firebaseio.com',
    storageBucket: 'schaty-7b3c3.appspot.com',
    androidClientId: '879205408677-lqnr69rm5vtga576sajo7lkv50383m94.apps.googleusercontent.com',
    iosClientId: '879205408677-ti8q7ofout1gt5ud4p3dgljdr2ba5s1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.schatty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgid1GAhGFUvRz7OdR7oOUIoN5FnCv0cI',
    appId: '1:879205408677:ios:5d5eb1ef3d4743cbee924c',
    messagingSenderId: '879205408677',
    projectId: 'schaty-7b3c3',
    databaseURL: 'https://schaty-7b3c3.firebaseio.com',
    storageBucket: 'schaty-7b3c3.appspot.com',
    androidClientId: '879205408677-lqnr69rm5vtga576sajo7lkv50383m94.apps.googleusercontent.com',
    iosClientId: '879205408677-ti8q7ofout1gt5ud4p3dgljdr2ba5s1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.schatty',
  );
}
